server:
  port: 8080

service:
  telegram:
    vip-group-id: -1001856345480
    private-group-id: -1002043576596
    test-group-id: -1002205997540
  bit-get:
    baseUrl: "https://api.bitget.com"
    endpoint:
      customer-list: "/api/broker/v1/agent/customerList"
      customer-deposit-list: "/api/broker/v1/agent/customerDepositList"
      customer-trade-volumn: "/api/broker/v1/agent/customerTradeVolumnList"
      customer-assets-list: "/api/broker/v1/agent/customerAccountAssetsList"
      server-time: "/api/v2/public/time"
  sqlite:
    database_uri: "sqlite:///erp4btc.db"
    track_modifications: false
    echo: false
    db-pool-size: 10
    db-pool-timeout: 30
    db-pool-recycle: 1800
    db-max-overflow: 5
  database:
    host: localhost
    port: 5432
    dbname: postgres
    url: postgres://${service.database.dbname}:${service.database.password}@${service.database.username}:${service.database.port}/${service.database.dbname}
    username: postgres
    password: pass
